### ISSUE TITLE
how to fix this error

### ISSUE THREAD

**Issue by adityakanungo12** [FirezTheGreat/1SHOT#40]
Fontconfig error: Cannot load default config file
/home/runner/1SHOT/handler/command.js:8
            bot.commands.set(pull.config.name, pull);
                                         ^

TypeError: Cannot read property 'name' of undefined
    at load (/home/runner/1SHOT/handler/command.js:8:42)
    at /home/runner/1SHOT/handler/command.js:12:116
    at Array.forEach (<anonymous>)
    at module.exports (/home/runner/1SHOT/handler/command.js:12:103)
    at /home/runner/1SHOT/index.js:15:71
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/1SHOT/index.js:15:33)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
exit status 1

every time I run It shows this error

**Comment by FirezTheGreat** [comment]
in every command's aliases make sure the aliases are inside `[]` like this `['alias1', 'alias2']`

**Comment by adityakanungo12** [comment]
Do I have to change where no alias is written

**Comment by adityakanungo12** [comment]
What code should I add for 24/7 music

**Comment by FirezTheGreat** [comment]
> Do I have to change where no alias is written

yes `noalias: []`
